name = "ModelingToolkitParameters"
uuid = "d96c1b6d-73fa-42cf-8af9-45e6140feccb"
authors = ["Brad Carman <bradleygcarman@outlook.com>"]
version = "0.3.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
InteractiveUtils = "1.11.0"
JuliaFormatter = "2.2.0"
ModelingToolkit = "10.30.0"
SciMLBase = "2.128.0"
SymbolicIndexingInterface = "0.3.46"
Symbolics = "6.58.0"
julia = "1"
