[deps]
ActiveSuspensionModel = "d21327f5-f906-4840-9bb0-2687f0591413"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitParameters = "d96c1b6d-73fa-42cf-8af9-45e6140feccb"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[sources]
ActiveSuspensionModel = {url = "https://github.com/bradcarman/ActiveSuspensionModel", subdir = "ActiveSuspensionModel.jl"}


